### ISSUE TITLE
Wrong answer

### ISSUE THREAD

**Issue by RUVATA** [artemdemo/frontend-interview-questions#1]
[https://github.com/artemdemo/frontend-interview-questions/blob/master/js-questions.md](ANSWER)
**Q.** You have variable that may or may not be a number. Write function isNumber() that will return true if it is in fact number or false otherwise.

**A.**
```
function isNumber(str) {
    return Number(str) == Number(str);
}
```

It's answer is bullshit  :) !
![image](https://user-images.githubusercontent.com/2040022/39646707-feb60b30-4fe4-11e8-8724-349fd1f4fccb.png)

see the 20.1.1.1, step 2 of ECMA Specification

> When Number is called with argument value, the following steps are taken:
> 1. If no arguments were passed to this function invocation, let n be +0.
> **2. Else, let n be ? ToNumber(value).**

Number constructor try value (argument) type conversion to number type, if it be possible
so realy Boolean, empty Array, empty string and other cases by weak comparison rules - this function take positive result, but it is wrong.

from the condition of question 
`hat will return true if it is in fact number or false otherwise.`
realy rigth answer is 
`function isNumber(arg) {
    return isNaN(arg) ? false
				: typeof arg === 'number' ? true : false	
}`
![image](https://user-images.githubusercontent.com/2040022/39647475-cf82858e-4fe7-11e8-9fa2-c51cbf1d2632.png)

**Comment by artemdemo** [comment]
I agree, question is misleading and answer is not covering all edge cases.
I fixed it. Closing

**Comment by RUVATA** [comment]
suggested variant is overly verbose
`function isNumber(value) {
    if (typeof value === 'string' && value !== '') {
        return Number(value) === Number(value);
    }
    return !isNaN(value) && typeof value === 'number';
}`

check typeof string and non equal to empty string - do not make sense
look at the option that I suggested above
`function isNumber(arg) { 
       return isNaN(arg) ? false 
              : typeof arg === 'number' ? true : false 
}`

it's be optimal to cover all border cases
may be code style does not provide abundance a lot of ternary operators
it may be rewrited in if-else-clean style
`function isNumber(arg) { 
       if (isNaN(arg)) {
             return false
       } else {
             return typeof arg === 'number'
       }
}`

**Comment by artemdemo** [comment]
Code should be verbose, so it will be easier to humans to read.
Now `isNumber()` answering the question. Make sure you read new version of it.

**Comment by RUVATA** [comment]
oh, sorry
I did not read the new version of the question
the new question itself became a bit confusing, as you think ?

**Comment by artemdemo** [comment]
Agree, it could be.
But it could be confusing in the interview as well.
If you have better version in mind, please share :)

**Comment by RUVATA** [comment]
I think the original version of the question was balanced
It not confusing but request for intervivable some specific knowledges:
1) correct usage of typeof applicability, IRL usages
2) NaN border case, as NaN !== NaN and NaN is type of number

and also see how a person will make a laconic utilitarian function

**Comment by artemdemo** [comment]
I believe there is place for both version of this question. I will keep both of them.
